### ISSUE TITLE
Boundaries not displayed while marking prominences

### ISSUE THREAD

**Issue by MatsRooth** [timmahrt/LMEDS#2]
I'm trying to use the boundary_and_prominence mode.  With the materials I created, things are working, except that the boundaries are not displayed consistently (often they are not displayed at all) when prominences are being marked.

My example is at https://github.com/MatsRooth/LMEDS.

I didn't get very far in using it, there could easily be something wrong with my configuration.

**Comment by timmahrt** [comment]
I've investigated and it is definitely a more recent bug in LMEDS.  The bug is tied to the length of the input.  LMEDS has been used with long inputs before just fine.  I have an idea of how to fix this but I don't have time today.  I will try and fix this tomorrow.

Sorry for the inconvenience.

**Comment by timmahrt** [comment]
Hi,
Thanks again for your bug report.  I tracked down the issue and fixed it.

I'm sorry again for the problem.  If you experience any other issues, please let me know.
Thank you,
Tim

**Comment by MatsRooth** [comment]
I am still seeing the same behavior on my example after the update.  I made some snapshots that can be seen at https://github.com/MatsRooth/LMEDS/blob/master/bug/p1.png and subsequent images.  
p2-p3 show the desirable behavior, where the boundary marks (vertical bars) have carried over when one clicks Continue to mark prominences.  In p4-p6 the boundaries did not carry over at all.  In p7-p9, two out of three boundaries carry over.

Could you check whether this example works in your environment?

Thanks in advance
Mats

**Comment by timmahrt** [comment]
I downloaded a fresh copy of LMEDS from github and dropped your testing files into it.  Before I made the fix I received the same behaviour that you saw but since making the fix I am able to run through your sequence without experiencing any "bad" behaviour.

Boundaries:
<img width="666" alt="Screen Shot 2019-05-30 at 9 30 35 PM" src="https://user-images.githubusercontent.com/2650064/58633115-7ebdb780-8322-11e9-94ed-721ea722621f.png">

Prominences:
<img width="654" alt="Screen Shot 2019-05-30 at 9 31 10 PM" src="https://user-images.githubusercontent.com/2650064/58633121-82513e80-8322-11e9-8ab3-887d04a23f93.png">

Could you try again?  If you are running LMEDS locally and you did not restart the python server when you updated, that could be the cause.  

I think it is unlikely, but the code could be cached in your browser.  You might try to do a hard refresh (command+shift+r in mac; ctrl + f5 in windows) in your browser and see if that fixes the problem

If you are still seeing the behaviour, could you verify that line the following line has been changed?
Line 53 and 54 of `html/b-p-scores.js`
https://github.com/timmahrt/LMEDS/commit/6eec30a5e556fd55564da849b79d177b4a1ab60f#diff-1e06aa74a5d596da68e136f414b1c9e8

If everything seems ok but you are still experiencing this problem, could you tell me more about your setup?  Python 2 or 3; browser; OS; running locally or remotely.  If there are any other details that you think might be relevant, please let me know.

Thanks and sorry again for the hassle,
Tim

**Comment by MatsRooth** [comment]
That was it, the browser was running the old version! Even restarting the laptop was no help, but clearing the Chrome browser cache cured it. Many thanks.
Mats

**Comment by timmahrt** [comment]
I'm glad to hear it!
